.github/CONTRIBUTING.md, README.md, src/main/java/uk/gov/hmcts/reform/pbis/Application.java, src/test/java/uk/gov/hmcts/reform/pbis/ApplicationTests.java
Update the description of the service in docs (it sends welcome emails, not invitation emails).
Also, change the base package name.
```
[ ] Yes
[x] No
```
=> Description and package corrections

src/main/java/uk/gov/hmcts/reform/pbis/EmailCreator.java, src/main/java/uk/gov/hmcts/reform/pbis/EmailSendingException.java, src/main/java/uk/gov/hmcts/reform/pbis/EmailService.java, src/main/java/uk/gov/hmcts/reform/pbis/model/EmailToSend.java, src/main/java/uk/gov/hmcts/reform/pbis/model/PrivateBetaRegistration.java, src/main/java/uk/gov/hmcts/reform/pbis/model/TemplateFieldNames.java, src/test/java/uk/gov/hmcts/reform/pbis/EmailCreatorTest.java, src/test/java/uk/gov/hmcts/reform/pbis/EmailServiceTest.java
https://tools.hmcts.net/jira/browse/RPE-80
Create a service for sending welcome emails. This includes a helper service for converting
private beta registrations into emails.
```
[ ] Yes
[x] No
```
=> Implement welcome email sending

src/main/java/uk/gov/hmcts/reform/pbis/EmailCreator.java, src/main/java/uk/gov/hmcts/reform/pbis/config/ApplicationConfig.java, src/main/java/uk/gov/hmcts/reform/pbis/notify/NotificationClientProvider.java, src/test/java/uk/gov/hmcts/reform/pbis/EmailCreatorTest.java, src/test/java/uk/gov/hmcts/reform/pbis/notify/NotificationClientProviderTest.java
Make configuration return dependencies of email service, rather than be injected as their dependency.
```
[ ] Yes
[x] No
```
=> Make configuration return dependencies of email service

.travis.yml
- include code coverage report generation in Travis
- specify JDK version
- run codacy reporter in travis build
```
[ ] Yes
[x] No
```
=> Check code coverage in Travis

build.gradle
Create XML report file on Jacoco step. Codacy coverage reporter needs it.
```
[ ] Yes
[x] No
```
=> Create XML report file on Jacoco step

Jenkinsfile
This change is a part of https://tools.hmcts.net/jira/browse/RPE-77
Add Jenkinsfile to the project
```
[ ] Yes
[x] No
```
=> Add Jenkinsfile to the project

build.gradle, web.config
Add web.config to the project, so that the service can be deployed to CNP. Also, set a fixed base name for the jar.
This is just a step toward the proper solution - eventually the name of the service in the jar will be specified in one place.
```
[ ] Yes
[x] No
```
=> Add web.config

README.md, build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/pbis/EndToEndTest.java, src/functionalTest/java/uk/gov/hmcts/reform/pbis/SubscriptionProcessingTest.java, src/functionalTest/java/uk/gov/hmcts/reform/pbis/categories/EndToEndTests.java, src/functionalTest/java/uk/gov/hmcts/reform/pbis/utils/NotificationHelper.java, src/functionalTest/java/uk/gov/hmcts/reform/pbis/utils/SampleData.java
https://tools.hmcts.net/jira/browse/RPE-91
Prepare end-to-end tests for coexisting with lower level integration tests by:
- renaming the test file, so that end-to-end tests are easily distinguishable
- introducing end-to-end test category and assigning it to existing tests, so that they can be executed separately
- extracting test utils that can be used by integration tests
```
[ ] Yes
[x] No
```
=> Prepare end-to-end tests for coexisting with lower level integration tests

src/functionalTest/java/uk/gov/hmcts/reform/pbis/integration/MessageQueueProcessorTest.java, src/main/java/uk/gov/hmcts/reform/pbis/MessageProcessingResult.java, src/main/java/uk/gov/hmcts/reform/pbis/MessageProcessingResultType.java, src/main/java/uk/gov/hmcts/reform/pbis/config/ApplicationConfig.java, src/main/java/uk/gov/hmcts/reform/pbis/model/PrivateBetaRegistration.java, src/main/java/uk/gov/hmcts/reform/pbis/servicebus/MessageQueueProcessor.java, src/test/java/uk/gov/hmcts/reform/pbis/servicebus/MessageQueueProcessorTest.java
https://tools.hmcts.net/jira/browse/RPE-112
Validate messages from Azure Service Bus before processing them.
```
[ ] Yes
[x] No
```
=> Validate messages from Azure Service Bus

src/test/java/uk/gov/hmcts/reform/pbis/ApplicationTest.java
Make the application unit test (loads context...) use dependency stubs and disable scheduled jobs.
```
[ ] Yes
[x] No
```
=> Make sure application unit test doesn't do any real work

build.gradle
Add sonarqube task to gradle build. The task is required by the pipeline.
```
[ ] Yes
[x] No
```
=> Add sonarqube task to gradle build

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/pbis/integration/MessageQueueProcessorTest.java, src/main/java/uk/gov/hmcts/reform/pbis/config/ApplicationConfig.java, src/main/java/uk/gov/hmcts/reform/pbis/servicebus/MessageQueueProcessor.java, src/main/java/uk/gov/hmcts/reform/pbis/telemetry/EventNames.java, src/main/java/uk/gov/hmcts/reform/pbis/telemetry/MetricNames.java, src/test/java/uk/gov/hmcts/reform/pbis/servicebus/MessageQueueProcessorTest.java
https://tools.hmcts.net/jira/browse/RPE-114
Send events and metrics to Application Insights
```
[ ] Yes
[x] No
```
=> Send metrics and events to Azure Application Insights

src/functionalTest/java/uk/gov/hmcts/reform/pbis/integration/MessageQueueProcessorTest.java, src/main/java/uk/gov/hmcts/reform/pbis/servicebus/MessageQueueProcessingTracker.java, src/main/java/uk/gov/hmcts/reform/pbis/servicebus/MessageQueueProcessor.java, src/test/java/uk/gov/hmcts/reform/pbis/servicebus/MessageQueueProcessingTrackerTest.java, src/test/java/uk/gov/hmcts/reform/pbis/servicebus/MessageQueueProcessorTest.java
https://tools.hmcts.net/jira/browse/RPE-114
Extract logging and telemetry from MessageQueueProcessor into MessageQueueProcessingTracker class.
```
[ ] Yes
[x] No
```
=> Extract logging and telemetry from MessageQueueProcessor

src/main/java/uk/gov/hmcts/reform/pbis/config/ApplicationConfig.java
Replace telemetry client bean with message processing tracker bean (that's the one injected in MessageQueueProcessor now).
```
[ ] Yes
[x] No
```
=> Replace telemetry client bean with message processing tracker bean

Jenkinsfile_CNP
Remove properties section from Jenkinsfile_CNP. This section is no longer necessary.
```
[ ] Yes
[x] No
```
=> Remove an unnecessary properties section from Jenkinsfile_CNP

infrastructure/main.tf, infrastructure/state.tf, infrastructure/terraform.sh, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RPE-195
Add Terraform related with CNP infrastructure (originally located in https://github.com/contino/moj-private-beta-invitation-infrastructure).
```
[ ] Yes
[x] No
```
=> Add Terraform files related with CNP infrastructure

build.gradle, src/main/java/uk/gov/hmcts/reform/pbis/config/ApplicationConfig.java, src/main/java/uk/gov/hmcts/reform/pbis/servicebus/MessageQueueProcessingTracker.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/pbis/ApplicationTest.java, src/test/java/uk/gov/hmcts/reform/pbis/servicebus/MessageQueueProcessingTrackerTest.java
Replacing insights direct dependency and using hmcts built-in implementation in `java-logging-appinsights` module.
```
[ ] Yes
[x] No
```
=> App insights: logging library

infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/confluence/display/CNP/Preview+Environment#PreviewEnvironment-Reducecapacity
=> Set node capacity for azure envs

build.gradle, web.config
Set up logging and remove version from jar name in web.config
```
[ ] Yes
[x] No
```
=> Set up logging and remove version from jar name in web.config

Jenkinsfile_CNP, infrastructure/main.tf, infrastructure/variables.tf
There's a max length for azure resource names
=> Shorter service name

infrastructure/main.tf, infrastructure/variables.tf
Will be used to setup secrets for tests (notify api key) and actual services on prod.
=> Setup vault

infrastructure/main.tf, src/main/resources/application.yaml
in order to run the tests, there needs to be a service configured in the application.
Tests using it to follow.
=> register service for tests

src/main/java/uk/gov/hmcts/reform/pbis/EmailCreator.java, src/main/java/uk/gov/hmcts/reform/pbis/EmailService.java, src/main/java/uk/gov/hmcts/reform/pbis/model/TemplateFieldNames.java, src/test/java/uk/gov/hmcts/reform/pbis/EmailCreatorTest.java
Just some tiny rafactoring to simplify things.
=> [SKIP-PREVIEW] Cleanup sending emails

.codecov.yml
https://docs.codecov.io/docs/commit-status
=> [SKIP-PREVIEW] Add codecov config file

Jenkinsfile_parameterized
Add Jenkinsfile_parameterized file, so that the service can be deployed to sandbox environments.
```
[ ] Yes
[x] No
```
=> Add Jenkinsfile_parameterized

build.gradle, dependency-check-suppressions.xml
Fix owasp dependency failures
```
[ ] Yes
[x] No
```
=> Fix owasp dependency failures

infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RPE-824
Add missing resource group tags
```
[ ] Yes
[x] No
```
=> Add missing resource group tags

build.gradle
=> updating PMD to 6.11

build.gradle
Disable .Net scanning in order to fix build failures
Disable .Net scanning
```
[ ] Yes
[x ] No
```
=> disable .Net scanning

build.gradle, dependency-check-suppressions.xml
NA
Bumping to latest versions, suppressing FPs
```
[ ] Yes
[x] No
```
=> Bumping to latest version, suppressing FPs

build.gradle
=> Upgrade to owasp 5

.travis.yml, build.gradle
=> updgrade jackson databind

Jenkinsfile_CNP, build.gradle, checkstyle.xml
=> fixing owasp, bumping checkstyle

dependency-check-suppressions.xml
[AB#697](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/697)
Added suppression for CVE that are not relevant
```
[ ] Yes
[x] No
```
=> added supression for CVE's

dependency-check-suppressions.xml
[AB#697](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/697)
Updated Supressions schema. This is backwards compatible with the previous schemas. 
https://www.bountysource.com/issues/78065928-suppression-xml-schema-question
```
[ ] Yes
[x] No
```
=> Updated Supressions schema
